services:
  - type: web
    name: my-wave-watcher
    env: node
    region: oregon
    plan: free
    buildCommand: ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # You'll add this manually in Render dashboard
      - key: PORT
        value: 5000
